"""queuejob nullable topic + exercise_id for duplicate_search

Revision ID: 2295db6ff51b
Revises: 56220802d7c5
Create Date: 2026-06-07 01:18:26.497805
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2295db6ff51b'
down_revision: str | None = '56220802d7c5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_id', sa.Integer(), nullable=True))
        batch_op.alter_column('topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('stage',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('formula', 'notes', 'assessment', 'duplicate_search', name='queuestage', native_enum=False),
               existing_nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_queue_jobs_exercise_id_extracted_exercises'), 'extracted_exercises', ['exercise_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_queue_jobs_exercise_id_extracted_exercises'), type_='foreignkey')
        batch_op.alter_column('stage',
               existing_type=sa.Enum('formula', 'notes', 'assessment', 'duplicate_search', name='queuestage', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('exercise_id')

    # ### end Alembic commands ###
