"""duplicator tables

Revision ID: 56220802d7c5
Revises: bc391d5c04ef
Create Date: 2026-06-07 00:33:47.534336
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import backend.db.types

# revision identifiers, used by Alembic.
revision: str = '56220802d7c5'
down_revision: str | None = 'bc391d5c04ef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('subtopic', sa.String(), nullable=True),
    sa.Column('year_level', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('own', 'imported', name='calibrationsource', native_enum=False), nullable=False),
    sa.Column('created_at', backend.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calibration_samples'))
    )
    op.create_table('exercise_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_hash', sa.String(), nullable=False),
    sa.Column('year_level', sa.Integer(), nullable=False),
    sa.Column('subject_hint', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('extracting', 'ready', 'error', name='exercisesessionstatus', native_enum=False), nullable=False),
    sa.Column('created_at', backend.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_sessions'))
    )
    op.create_table('extracted_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('subtopic', sa.String(), nullable=True),
    sa.Column('difficulty_signals', sa.JSON(), nullable=False),
    sa.Column('viz', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'searching', 'done', 'error', name='exercisestatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['exercise_sessions.id'], name=op.f('fk_extracted_exercises_session_id_exercise_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracted_exercises'))
    )
    op.create_table('duplicate_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('problem_text', sa.String(), nullable=False),
    sa.Column('viz', sa.JSON(), nullable=True),
    sa.Column('difficulty_score', sa.Float(), nullable=True),
    sa.Column('queue_job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['extracted_exercises.id'], name=op.f('fk_duplicate_results_exercise_id_extracted_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_job_id'], ['queue_jobs.id'], name=op.f('fk_duplicate_results_queue_job_id_queue_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duplicate_results'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('duplicate_results')
    op.drop_table('extracted_exercises')
    op.drop_table('exercise_sessions')
    op.drop_table('calibration_samples')
    # ### end Alembic commands ###
