"""add note_attachments

Revision ID: bc391d5c04ef
Revises: b9c0d1e2f3a4
Create Date: 2026-06-05 22:53:06.965876
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import backend.db.types

# revision identifiers, used by Alembic.
revision: str = 'bc391d5c04ef'
down_revision: str | None = 'b9c0d1e2f3a4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('created_at', backend.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_note_attachments_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note_attachments'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_attachments')
    # ### end Alembic commands ###
