"""Shared enums for the ORM, exactly per docs/architecture.md.

Stored as plain strings (``native_enum=False``) and validated in Python via
these ``StrEnum`` classes — SQLite has no native enum type.
"""

import enum


class DocumentStatus(enum.StrEnum):
    # Audio documents are transcribed before structure review; until the transcript
    # is ready they sit in ``transcribing`` (or ``error`` if transcription failed /
    # was rate-limited — see Document.status_detail). PDFs skip straight to
    # ``uploaded``.
    transcribing = "transcribing"
    uploaded = "uploaded"
    processing = "processing"
    ready = "ready"
    error = "error"


class DocumentMode(enum.StrEnum):
    """How a document is processed and presented.

    ``study`` (default) is the full pipeline: notes + MCQs + flashcards, with the
    formula vision stage. ``exam`` is assessment-only — the generation call drops
    notes and the formula stage is skipped, so the document yields just MCQs (with
    explanations) and flashcards. Drives the dedicated Exam Prep section.
    """

    study = "study"
    exam = "exam"


class TopicPriority(enum.StrEnum):
    exam_critical = "exam_critical"
    medium = "medium"
    skip = "skip"  # never sent to a model


class TopicStatus(enum.StrEnum):
    queued = "queued"
    processing = "processing"
    ready = "ready"
    error = "error"


class QueueStage(enum.StrEnum):
    formula = "formula"
    notes = "notes"
    assessment = "assessment"
    # Exercise Duplicator Stage 2 (independent of formula/notes/assessment). These
    # jobs carry an exercise reference instead of a topic and are drained by a
    # dedicated search loop, NOT the topic/lane generation path. Appended last so
    # existing STAGE_RANK values are unchanged (rank is unused for these jobs —
    # they never enter priority sort or stage-prerequisite checks).
    duplicate_search = "duplicate_search"


class QueueState(enum.StrEnum):
    pending = "pending"
    running = "running"
    done = "done"
    failed = "failed"


class QueueLaneState(enum.StrEnum):
    """Per-subject queue lane state (Wave B).

    A subject's lane processes its topics independently of other subjects'. It is
    ``running`` normally, ``paused`` when the user hard-stops new dispatch for that
    lane only (Steam-download model), or ``overnight`` to grind everything on free
    tiers across reset windows (per-subject, not global).
    """

    running = "running"
    paused = "paused"
    overnight = "overnight"


class FormulaState(enum.StrEnum):
    pending = "pending"  # region detected/registered; vision transcription deferred
    reconstructed = "reconstructed"
    verified = "verified"


class HistoryEventType(enum.StrEnum):
    """Notable, append-only generation-history events (Wave C).

    Replaces the previously-planned overnight notification: instead of pushing a
    notification, the app keeps a visible chronological log. ``topic_generated``
    records which topic was made by which provider and how long it took;
    ``provider_switch`` records when the active provider changed (e.g. Ollama→Gemini
    at a reset window).
    """

    topic_generated = "topic_generated"
    provider_switch = "provider_switch"


class LocalAiStatus(enum.StrEnum):
    """Lifecycle of the local AI setup flow (services/local_ai/setup.py).

    ``detected`` holds the hardware + selection snapshot awaiting the user's
    Stage 5 confirmation; ``queued`` → ``installing_ollama`` → ``pulling`` are
    the install worker's phases (resumable across restarts); ``ready`` means
    both models are pulled and the settings point at them.
    """

    not_configured = "not_configured"
    detected = "detected"
    queued = "queued"
    installing_ollama = "installing_ollama"
    pulling = "pulling"
    ready = "ready"
    failed = "failed"


class ScheduleSource(enum.StrEnum):
    sm2 = "sm2"
    manual = "manual"  # user-created/moved (custom events, topic/subject sessions, drag-drop)
    deadline = "deadline"
    ai = "ai"  # generated by the AI study planner; preserved across SM-2 rebuilds


class ExerciseSessionStatus(enum.StrEnum):
    """Lifecycle of an Exercise Duplicator session (the uploaded exercise PDF).

    Synchronous Stage-1 extraction flips ``extracting`` → ``ready`` (or ``error``);
    the per-exercise variant search runs afterwards on the queue and lives on
    ``ExtractedExercise.status``, not here.
    """

    extracting = "extracting"
    ready = "ready"
    error = "error"


class ExerciseStatus(enum.StrEnum):
    """Per-exercise variant-search state (Exercise Duplicator Stage 2).

    ``pending`` until a queue job claims it, ``searching`` while it runs, ``done``
    once variants are written, ``error`` on terminal failure.
    """

    pending = "pending"
    searching = "searching"
    done = "done"
    error = "error"


class CalibrationSource(enum.StrEnum):
    """Where a calibration sample came from: the user's own uploads vs. an import.

    Member name == value (the repo-wide ``StrEnum`` convention — ``SAEnum`` stores
    the member *name*). ``import`` is a reserved keyword, so the member is
    ``imported`` rather than the spec's bare ``import``.
    """

    own = "own"
    imported = "imported"
